version: "3.8"

services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DATABASE_URL: Host=db;Database=task_management;Username=postgres;Password=password
    depends_on:
      - db

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
